[package]
name = "asicamera2"
version = "0.14.1119"
authors = ["Victor R. Ruiz <rvr@redhat.com>"]
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
bindgen = ""
